"""create social_posts table

A separate table from jobs, not a shared one: a video job and a post fail
differently. Re-running a dead video job just burns image quota; re-running
a dead post publishes the same text twice (the X API has no idempotency
key). This table's status column therefore includes NEEDS_REVIEW, a state
with no equivalent on the jobs side.

Revision ID: 4443966ca043
Revises: 431d97290b12
Create Date: 2026-08-15 20:59:38.251209

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4443966ca043"
down_revision: str | Sequence[str] | None = "431d97290b12"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "social_posts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("group_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.String(length=64), nullable=False),
        sa.Column("article_title", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("weighted_length", sa.Integer(), nullable=False),
        sa.Column("has_link", sa.Boolean(), nullable=False),
        sa.Column("image_key", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tweet_id", sa.String(length=32), nullable=True),
        sa.Column("reply_to_tweet_id", sa.String(length=32), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("social_posts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_social_posts_article_id"), ["article_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_social_posts_group_id"), ["group_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_social_posts_status"), ["status"], unique=False)
        batch_op.create_index(
            "ix_social_posts_status_scheduled_at", ["status", "scheduled_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("social_posts", schema=None) as batch_op:
        batch_op.drop_index("ix_social_posts_status_scheduled_at")
        batch_op.drop_index(batch_op.f("ix_social_posts_status"))
        batch_op.drop_index(batch_op.f("ix_social_posts_group_id"))
        batch_op.drop_index(batch_op.f("ix_social_posts_article_id"))

    op.drop_table("social_posts")
    # ### end Alembic commands ###
